### ISSUE TITLE
No indication that a module is an introduction

### ISSUE THREAD

**Issue by Dantemss** [Rhaptos/Products.CNXMLTransforms#1]
Would be nice to have some indication in the collection JSON or module HTML when a module is a chapter introduction.

**Comment by philschatz** [comment]
I believe an intro module CNXML has `class="introduction"` on it (PDF uses it for styling). Not sure if that attribute is translated into the HTML (but it should be)

**Comment by Dantemss** [comment]
It's not, hence the bug report :)

**Comment by edwoodward** [comment]
Moved to https://github.com/Connexions/rhaptos.cnxmlutils/issues/129 so closing.
